"""empty message

Revision ID: 0a66266dc8de
Revises: 
Create Date: 2017-12-05 02:47:17.539023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a66266dc8de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_bonuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invester_account_id', sa.Integer(), nullable=False),
    sa.Column('earned_account_id', sa.Integer(), nullable=False),
    sa.Column('invested_amount', sa.Float(), nullable=False),
    sa.Column('earned_amount', sa.Float(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['earned_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_bonuses_earned_account_id'), 'referral_bonuses', ['earned_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referral_bonuses_earned_account_id'), table_name='referral_bonuses')
    op.drop_table('referral_bonuses')
    # ### end Alembic commands ###
