"""empty message

Revision ID: 6fca440ab679
Revises: 
Create Date: 2017-12-01 02:45:37.750951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fca440ab679'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_investments', sa.Column('paymentSystemId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'account_investments', 'payment_systems', ['paymentSystemId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account_investments', type_='foreignkey')
    op.drop_column('account_investments', 'paymentSystemId')
    # ### end Alembic commands ###
