"""empty message

Revision ID: 9dd2b8e4a995
Revises: 
Create Date: 2017-12-08 01:53:19.101314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd2b8e4a995'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral_bonuses', sa.Column('dateTime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referral_bonuses', 'dateTime')
    # ### end Alembic commands ###
