"""empty message

Revision ID: f82eb587bf94
Revises: 
Create Date: 2017-12-14 03:09:06.228876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f82eb587bf94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_investments', sa.Column('payment_unit', sa.String(length=10), nullable=True))
    op.add_column('account_investments', sa.Column('pm_batch_num', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_investments', 'pm_batch_num')
    op.drop_column('account_investments', 'payment_unit')
    # ### end Alembic commands ###
